### PR TITLE
Fallback to v1.2.9. Added some handling to stand inplace of the manual file corruption check.

### PR DESCRIPTION
**Pull request by J-Stuff**
After some more debugging, it looked best to fall back to v1.2.9 and add a try/except statement on the original line of code that was causing the errors in #191 

The manual check with integv only caused issues in prod after the Dockerfile was built. So this should avoid it entirely.
(Shane, I thank you immensely for putting up with this tom-fuckery of an idea)

### CODE REVIEW

**Comment by J-Stuff** [comment]
I found the issue in #191 was caused when recording using NVIDIA shadow play to the captures directory of Fireshare. Since the file was not fully "built" when fireshare attempted to scan the file.

**Comment by ShaneIsrael** [comment]
@J-Stuff No problem! Some improvements take a couple PR's to get right. I wish I had the time right now to help a bit more with it.

**Comment by ShaneIsrael** [comment]
I'll leave it in the develop build for now, let me know if you think its all good and I'll merge to main and do another release.

**Comment by J-Stuff** [comment]
Thanks. Would it be possible for a develop Dockerfile to be built for testing. As I'm unable to build a working dockerfile for some reason.

**Comment by J-Stuff** [comment]
Thanks. Would it be possible for a develop Dockerfile to be built for testing. As I'm unable to build a working dockerfile for some reason.

**Comment by ShaneIsrael** [comment]
The develop branch has always had a docker image built when it is updated. its `fireshare:develop`, when you run it though the version will still reflect whatever the current main version is set to since I don't update develops version until I'm ready to make a new release.

**Pull request merged**
