### PR TITLE
feat(add): Upload when drag and drop

### LINKED ISSUE #214: [Suggestion] Drag and drop should be there (like really)
the title say all

### PR DESCRIPTION
**Pull request by RisedSky**
closes #214 

This has been tested on my own instance and it's working as expected.

### CODE REVIEW

**Comment by RisedSky** [comment]
Any idea if you can check and accept this PR please ? @ShaneIsrael

**Comment by ShaneIsrael** [comment]
Hi, sorry I never saw this for some reason GitHub isn't sending me notifications for anything anymore. I'll try to look at this and the other issues that got created later this morning.

**Comment by ShaneIsrael** [comment]
@RisedSky Please update to remove semi-colons. If you're using vscode the client folder has a .prettierrc file which if used with the prettier plugin should format your code in the coding style I have set. 

Once that's updated I'll be happy to merge.

**Comment by RisedSky** [comment]
Alright thank you, I'll do the changes ASAP.

**Comment by RisedSky** [comment]
This should be good now

**Pull request merged**
